workflow:

  reflection:
    - schema_linking
    - generate_sql
    - execute_sql
    - reflect
    - output

  fixed:
    - schema_linking
    - generate_sql
    - execute_sql
    - output

  empty: []

  dynamic:
    - schema_linking
    - generate_sql
    - execute_sql
    - reflect
    - output

  metric_to_sql:
    - schema_linking
    - search_metrics
    - date_parser
    - generate_sql
    - execute_sql
    - output

  # Agentic workflow using ChatAgenticNode
  chat_agentic:
    - chat
    - execute_sql
    - output

  # Dedicated workflow for plan mode - chat node handles everything internally
  chat_agentic_plan:
    - chat
    - output

  gensql_agentic:
    - chatbot
    - execute_sql
    - output

  # Text2SQL workflow with preflight evidence and structured generation
  # Legacy names: text2sql_standard, nl2sql (mapped at API level for backward compatibility)
  text2sql:
    - intent_analysis      # Analyze query intent
    - schema_discovery     # Discover relevant schema
    - generate_sql         # Generate SQL with evidence
    - execute_sql          # Execute SQL query
    - output               # Return results
