workflow:

  reflection:
    - schema_linking
    - generate_sql
    - execute_sql
    - reflect
    - output

  fixed:
    - schema_linking
    - generate_sql
    - execute_sql
    - output

  empty: []

  dynamic:
    - schema_linking
    - generate_sql
    - execute_sql
    - reflect
    - output

  metric_to_sql:
    - schema_linking
    - search_metrics
    - date_parser
    - generate_sql
    - execute_sql
    - output

  # Agentic workflow using ChatAgenticNode
  chat_agentic:
    - chat
    - execute_sql
    - output

  # Dedicated workflow for plan mode - chat node handles everything internally
  chat_agentic_plan:
    - chat
    - output

  gensql_agentic:
    - chatbot
    - execute_sql
    - output
