workflow:
  # Reflection-based SQL generation workflow
  reflection:
    - schema_discovery
    - generate_sql
    - execute_sql
    - reflect
    - output

  # Fixed SQL generation workflow (no reflection)
  fixed:
    - schema_discovery
    - generate_sql
    - execute_sql
    - output

  empty: []

  # Dynamic SQL generation workflow
  dynamic:
    - schema_discovery
    - generate_sql
    - execute_sql
    - reflect
    - output

  # Metric-based SQL generation workflow
  metric_to_sql:
    - schema_discovery
    - search_metrics
    - date_parser
    - generate_sql
    - execute_sql
    - output

  # Interactive chat workflow for multi-turn conversations
  chat_agentic:
    - chat_agentic
    - execute_sql
    - output

  # Plan mode workflow for execution planning
  chat_agentic_plan:
    - chat_agentic
    - output

  # Focused SQL generation with enhanced context
  gensql_agentic:
    - sql_chatbot
    - execute_sql
    - output

  # Text2SQL workflow with comprehensive validation and reflection
  text2sql:
    - intent_analysis # Analyze query intent (task type detection)
    - intent_clarification # Clarify business intent (typos, ambiguities, entities)
    - schema_discovery # Discover relevant schema using clarified intent
    - schema_validation # Validate schema sufficiency
    - generate_sql # Generate SQL query
    - sql_validate # Validate SQL syntax and semantics
    - execute_sql # Execute SQL query
    - result_validation # Validate result quality
    - reflect # Reflect and self-correct if needed
    - output # Return results
